services:
  db:
    container_name: ticketing_db
    image: postgres:17
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
